sjybookstore/books/urls.py
from django.conf.urls import url
from books import views

urlpatterns = [
    url(r'^$', views.index, name='index'), # 首页
    url(r'^books/(?P<books_id>\d+)/$', views.detail, name='detail'),
]

sjybookstore/sjybookstore/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('books.urls', namespace='books')),
]

sjybookstore/users/urls.py
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'), 
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_check/$', views.login_check, name='login_check'),
    url(r'^logout/$', views.logout, name='logout'),
]

sjybookstore/books/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField
from books.enums import *
# Create your models here.

class BooksManager(models.Manager):
    def get_books_by_type(self, type_id, limit=None, sort='default'):
        if sort == 'new':
            order_by = ('-create_time',)
        elif sort == 'hot':
            order_by = ('-sales',)
        elif sort == 'price':
            order_by = ('price',)
        else:
            order_by =('-pk',)
        books_li = self.filter(type_id=type_id).order_by(*order_by)
        if limit:
            books_li = books_li[:limit]
        return books_li
    def get_books_by_id(self,book_id):
        try:
            books = self.get(id=books_id)
        except self.model.DoesNotExist:
            books = None
        return books


class Books(BaseModel):
    books_type_choices = ((k,v) for k,v in BOOKS_TYPE.items())
    status_choices = ((k,v) for k,v in STATUS_CHOICE.items())
    type_id = models.SmallIntegerField(default=PYTHON, choices=books_type_choices, verbose_name='商品种类')
    name = models.CharField(max_length=20, verbose_name='商品名称')
    desc = models.CharField(max_length=128, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    unit = models.CharField(max_length=20, verbose_name='商品单位')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    detail = HTMLField(verbose_name='商品详情')
    image = models.ImageField(upload_to='books', verbose_name='商品图片')
    status = models.SmallIntegerField(default=ONLINE, choices=status_choices, verbose_name='商品状态')
    objects = BooksManager()
    def __str__(self):
        return self.name
    class Meta:
        db_table = 's_books'
        verbose_name='书籍'
        verbose_name_plural=verbose_name

sjybookstore/books/views.py
from django.shortcuts import render
from books.models import Books
from books.enums import *
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
# Create your views here.
def index(request):
    python_new = Books.objects.get_books_by_type(PYTHON, limit=3, sort='new')
    python_hot = Books.objects.get_books_by_type(PYTHON, limit=4, sort='hot')
    javascript_new = Books.objects.get_books_by_type(JAVASCRIPT, limit=3, sort='new')
    javascript_hot = Books.objects.get_books_by_type(JAVASCRIPT, limit=4, sort='hot')
    algorithms_new = Books.objects.get_books_by_type(ALGORITHMS, limit=3, sort='new')
    algorithms_hot = Books.objects.get_books_by_type(ALGORITHMS, limit=3, sort='hot')
    machinelearning_new = Books.objects.get_books_by_type(MACHINELEARNING, 3, sort='new')
    machinelearning_hot = Books.objects.get_books_by_type(MACHINELEARNING, 4, sort='hot')
    operatingsystem_new = Books.objects.get_books_by_type(OPERATINGSYSTEM, 3, sort='new')
    operatingsystem_hot = Books.objects.get_books_by_type(OPERATINGSYSTEM, 4, sort='hot')
    database_new = Books.objects.get_books_by_type(DATABASE, 3, sort='new')
    database_hot = Books.objects.get_books_by_type(DATABASE, 4, sort='hot')

    context = {
        'python_new': python_new,
        'python_hot': python_hot,
        'javascript_new': javascript_new,
        'javascript_hot': javascript_hot,
        'algorithms_new': algorithms_new,
        'algorithms_hot': algorithms_hot,
        'machinelearning_new': machinelearning_new,
        'machinelearning_hot': machinelearning_hot,
        'operatingsystem_new': operatingsystem_new,
        'operatingsystem_hot': operatingsystem_hot,
        'database_new': database_new,
        'database_hot': database_hot,
    }
    return render(request, 'books/index.html',context)
def detail(request, books_id):
    books = Books.objects.get_books_by_id(books_id=books_id)
    if books is None:
        return redirect(reverse('books:index'))
    books_li = Books.objects.get_books_by_type(type_id=books.type_id, limit=2, sort='new')
    type_title = BOOKS_TYPE[books.type_id]
    context = {'books':books, 'books_li':books_li, 'type_title': type_title}
    return render(request, 'books/detail.html', context)
def list(request, type_id, page):
    sort = request.GET.get('sort', 'default')
    if int(type_id) not in BOOKS_TYPE.keys():
        return redirect(reverse('books:index'))
    books_li = Books.objects.get_books_by_type(type_id=type_id, sort=sort)
    paginator = Paginator(books_li, 1)
    num_pages = paginator.num_pages
    if page == '' or int(page) > num_pages:
        page = 1
    else:
        page = int(page)
    books_li = paginator.page(page)
    if num_pages < 5:
        pages = range(1, num_pages+1)
    elif page <= 3:
        pages = range(1, 6)
    elif num_pages - page <= 2:
        pages = range(num_pages-4, num_pages+1)
    else:
        pages = range(page-2, page+3)
    books_new = Books.objects.get_books_by_type(type_id=type_id, limit=2, sort='new')
    type_title = BOOKS_TYPE[int(type_id)]
    context = {
        'books_li': books_li,
        'books_new': books_new,
        'type_id': type_id,
        'sort': sort,
        'type_title':type_title,
        'pages':pages
    }
    return render(request, 'books/list.html', context)

sjybookstore/templates/books/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock title %}
{% block topfiles %}
<script>
$(function () {
    update_total_price()
    // 计算总价
    function update_total_price() {
        // 获取商品的价格和数量
        books_price = $('.show_pirze').children('em').text()
        books_count = $('.num_show').val()
        // 计算商品的总价
        books_price = parseFloat(books_price)
        books_count = parseInt(books_count)
        total_price = books_price * books_count
        // 设置商品总价
        $('.total').children('em').text(total_price.toFixed(2) + '元')
    }

    // 商品增加
    $('.add').click(function () {
        // 获取商品的数量
        books_count = $('.num_show').val()
        // 加1
        books_count = parseInt(books_count) + 1
        // 重新设置值
        $('.num_show').val(books_count)
        // 计算总价
        update_total_price()
    })

    // 商品减少
    $('.minus').click(function () {
        // 获取商品的数量
        books_count = $('.num_show').val()
        // 加1
        books_count = parseInt(books_count) - 1
        if (books_count == 0){
            books_count = 1
        }
        // 重新设置值
        $('.num_show').val(books_count)
        // 计算总价
        update_total_price()
    })

    // 手动输入
    $('.num_show').blur(function () {
        // 获取商品的数量
        books_count = $(this).val()
        // 数据校验
        if (isNaN(books_count) || books_count.trim().length == 0 || parseInt(books_count) <= 0 ){
            books_count = 1
        }
        // 重新设置值
        $('.num_show').val(parseInt(books_count))
        // 计算总价
        update_total_price()
    })
})
</script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="python">Python</a></li>
					<li><a href="#" class="javascript">Javascript</a></li>
					<li><a href="#" class="algorithms">数据结构与算法</a></li>
					<li><a href="#" class="machinelearning">机器学习</a></li>
					<li><a href="#" class="operatingsystem">操作系统</a></li>
					<li><a href="#" class="database">数据库</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">Python</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="book_detail_con clearfix">
		<div class="book_detail_pic fl"><img src="{% static books.image %}"></div>

		<div class="book_detail_list fr">
			<h3>{{ books.name }}</h3>
			<p>{{ books.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ books.price }}</em></span>
				<span class="show_unit">单  位：{{ books.unit }}</span>
			</div>
			<div class="book_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>100元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" books_id="{{ books.id }}" class="add_cart" id="add_cart">加入购物车</a>
				<a href="#" id="write-comment" class="comment">我要写评论</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_book">
				<h3>新品推荐</h3>
				<ul>
                    {% for book in books_li %}
					<li>
						<a href="{% url 'books:detail' books_id=books.id %}"><img src="{% static book.image %}"></a>
						<h4><a href="{% url 'books:detail' books_id=books.id %}">{{ book.name }}</a></h4>
						<div class="prize">￥{{ book.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active" id="detail">商品介绍</li>
				<li id="comment">评论</li>
			</ul>

			<div class="tab_content">
				<dl id="book_detail">
					<dt>商品详情：</dt>
					<dd>{{ books.detail | safe }}</dd>
				</dl>
				<dl id="book_comment">
				</dl>
			</div>

		</div>
	</div>
	<div class="add_jump"></div>
{% endblock body %}
{% block bottomfiles %}
<script type="text/javascript">
	$('#add_cart').click(function(){
        // 获取商品的id和商品数量
        var books_id = $(this).attr('books_id');
        var books_count = $('.num_show').val();
        var csrf = $('input[name="csrfmiddlewaretoken"]').val();
        // 发起请求，访问/cart/add/, 进行购物车数据的添加
        var params = {
        	'books_id': books_id, 
        	'books_count': books_count,
            'csrfmiddlewaretoken': csrf
        }

        $.post('/cart/add/', params, function (data) {
            if (data.res == 5){
                // 添加成功
				var count = $('#show_count').html();
				var count = parseInt(count) + parseInt(books_count);
				$('#show_count').html(count);
            }
            else {
                // 添加失败
                alert(data.errmsg);
            }
        })
	})

	$('#write-comment').click(function() {
		window.open("{% url 'comment:comment' book_id=books.id %}")
	})
</script>
    <style type="text/css">
        .comment {
            background-color: #c40000;
            color: #fff;
            margin-left: 10px;
            position: relative;
            z-index: 10;
            display: inline-block;
            width: 178px;
            height: 38px;
            border: 1px solid #c40000;
            font-size: 14px;
            line-height: 38px;
            text-align: center;
        }
    </style>
{% endblock bottomfiles %}

sjybookstore/templates/books/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{%load staticfiles%}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>尚硅谷书城-首页</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到尚硅谷书城!</div>
			<div class="fr">
            {% if request.session.islogin %}
				<div class="login_info fl">
					欢迎您：<em>{{ request.session.username }}</em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}>退出</a>
				</div>
            {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
            {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="book_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="python">Python</a></li>
			<li><a href="#model02" class="javascript">Javascript</a></li>
			<li><a href="#model03" class="algorithms">数据结构与算法</a></li>
			<li><a href="#model04" class="machinelearning">机器学习</a></li>
			<li><a href="#model05" class="operatingsystem">操作系统</a></li>
			<li><a href="#model06" class="database">数据库</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg" style="width: 240px; height: 135px;"></a>
			<a href="#"><img src="/static/images/adv02.jpg" style="width: 240px; height: 135px;"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">Python</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">Python核心编程</a>
				<a href="#">笨办法学Python</a>
				<a href="#">Python学习手册</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="images/banner01.jpg"></div>
			<ul class="book_list fl">
                {%for book in python_hot%}
				<li>
					<h4><a href="#">{{ book.name }}</a></h4>
					<a href="#"><img src="{% static book.image %}"></a>
					<div class="prize">{{ book.price }}</div>
				</li>
                {%endfor%}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">Javascript</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">Javascript高级编程</a>
				<a href="#">Javascript语言精粹</a>				
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner02.jpg"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">Javascript高级程序设计</a></h4>
					<a href="#"><img src="/static/images/book/book005.jpg"></a>
					<div class="prize">¥ 48.00</div>
				</li>
				<li>
					<h4><a href="#">Javascript权威指南</a></h4>
					<a href="#"><img src="/static/images/book/book006.jpg"></a>
					<div class="prize">¥ 46.00</div>
				</li>
				<li>
					<h4><a href="#">Javascript语言精粹</a></h4>
					<a href="#"><img src="{% static 'images/book/book007.jpg'%}"></a>
					<div class="prize">¥ 19.00</div>
				</li>
				<li>
					<h4><a href="#">Javascript DOM编程艺术</a></h4>
					<a href="#"><img src="{%static 'images/book/book008.jpg'%}"></a>
					<div class="prize">¥ 25.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">数据结构与算法</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">算法导论</a>
				<a href="#">数据结构与算法分析</a>
				<a href="#">计算机程序设计艺术</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner03.jpg' %}"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">数据结构与算法分析</a></h4>
					<a href="#"><img src="{% static 'images/book/book009.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">算法导论</a></h4>
					<a href="#"><img src="{% static 'images/book/book010.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">算法</a></h4>
					<a href="#"><img src="{% static 'images/book/book011.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">计算机程序设计艺术</a></h4>
					<a href="#"><img src="{% static 'images/book/book012.jpg'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">机器学习</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">机器学习</a>
				<a href="#">统计学习方法</a>
				<a href="#">集体智慧编程</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner04.jpg' %}"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">机器学习</a></h4>
					<a href="#"><img src="{% static 'images/book/book013.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">机器学习实战</a></h4>
					<a href="#"><img src="{% static 'images/book/book014.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">统计学习方法</a></h4>
					<a href="#"><img src="{% static 'images/book/book015.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">集体智慧编程</a></h4>
					<a href="#"><img src="{% static 'images/book/book016.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">操作系统</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">UNIX环境高级编程</a>
				<a href="#">深入理解计算机系统</a>
				<a href="#">现代操作系统</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner05.jpg' %}"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">现代操作系统</a></h4>
					<a href="#"><img src="{% static 'images/book/book017.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">深入理解计算机系统</a></h4>
					<a href="#"><img src="{% static 'images/book/book018.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">UNIX环境高级编程</a></h4>
					<a href="#"><img src="{% static 'images/book/book019.jpg' %}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">鸟哥的私房菜</a></h4>
					<a href="#"><img src="images/book/book020.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">数据库</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">数据库系统概念</a>
				<a href="#">高性能MySQL</a>
				<a href="#">MySQL必知必会</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner06.jpg' %}"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">数据库系统概念</a></h4>
					<a href="#"><img src="images/book/book021.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">高性能MySQL</a></h4>
					<a href="#"><img src="images/book/book022.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">Redis实战</a></h4>
					<a href="#"><img src="images/book/book023.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">Redis设计与实现</a></h4>
					<a href="#"><img src="images/book/book024.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京尚硅谷信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
</body>
</html>